[package]
name = "coffer"
version = "0.1.0"
authors = ["john <799433746@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
