TARGET := "riscv64imac-unknown-none-elf"
BINARY := "qemu"
PAYLOAD := "target/"+TARGET+"/debug/"+BINARY
RELEASE := "target/"+TARGET+"/release/"+BINARY

build:
  cargo build
  rust-objcopy {{PAYLOAD}} -O binary  qemu.striped

test:
  cargo build --tests --release
  qemu-system-riscv64  -machine sifive_u -bios {{RELEASE}} -nographic

release:
  cargo build --release
  for sec in 'abbrev' 'addr' 'aranges' 'info' 'line' 'line_str' 'ranges' 'rnglists' 'str' 'str_offsets'; do \
    rust-objcopy {{RELEASE}} --remove-section .rvbt_$sec; \
  done
  rust-objcopy -g {{RELEASE}}
  rust-objcopy {{RELEASE}} -O binary qemu.striped

xfel:
  xfel version
  xfel ddr ddr3
  xfel write 0x40000000 qemu.striped
  xfel exec 0x40000000

copy-debug:
	for sec in 'abbrev' 'addr' 'aranges' 'info' 'line' 'line_str' 'ranges' 'rnglists' 'str' 'str_offsets'; do \
		rust-objcopy {{PAYLOAD}} --dump-section .debug_$sec=tmp_$sec; \
		riscv64-unknown-elf-objcopy {{PAYLOAD}} --update-section .rvbt_$sec=tmp_$sec; \
	done
	rm tmp*; 

qemu-m MACHINE: build copy-debug
	qemu-system-riscv64 -machine {{MACHINE}} -bios {{PAYLOAD}} -nographic

qemu: build copy-debug
	qemu-system-riscv64 -machine sifive_u -bios {{PAYLOAD}} -nographic

gdb: build copy-debug
	qemu-system-riscv64 -S -s -machine sifive_u -bios {{PAYLOAD}} -nographic

gdb-m MACHINE: build copy-debug
	qemu-system-riscv64 -S -s -machine {{MACHINE}} -bios {{PAYLOAD}} -nographic
