TARGET := "riscv64imac-unknown-none-elf"
BINARY := "qemu"
PAYLOAD := "target/"+TARGET+"/debug/"+BINARY

build:
	cargo build

copy-debug:
	for sec in 'abbrev' 'addr' 'aranges' 'info' 'line' 'line_str' 'ranges' 'rnglists' 'str' 'str_offsets'; do \
		eval "rust-objcopy {{PAYLOAD}} --dump-section .debug_$sec=tmp_$sec"; \
		riscv64-unknown-elf-objcopy {{PAYLOAD}} --update-section .rvbt_$sec=tmp_$sec; \
	done
	rm tmp*; 

qemu-m MACHINE: build copy-debug
	qemu-system-riscv64 -machine {{MACHINE}} -bios {{PAYLOAD}} -nographic

qemu: build copy-debug
	qemu-system-riscv64 -machine sifive_u -bios {{PAYLOAD}} -nographic

gdb: build copy-debug
	qemu-system-riscv64 -S -s -machine sifive_u -bios {{PAYLOAD}} -nographic

gdb-m MACHINE: build copy-debug
	qemu-system-riscv64 -S -s -machine {{MACHINE}} -bios {{PAYLOAD}} -nographic
